/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Conexion.Queries;
import javax.swing.JOptionPane;
import Escritorio.Escritorio;
/**
 *
 * @author pc personal
 */
public class Acceso extends javax.swing.JFrame {
    private RegistrarEstudiantes regEst;
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        setLocationRelativeTo(null);
        regEst = new RegistrarEstudiantes();
    }
    
    private void BotonAcceso() {

    String usuario = UsuarioTxt.getText();
    String clave = new String(ClavePwd.getPassword());
    
    Queries ConsultaAcceso = new Queries();
    
    boolean esValido = ConsultaAcceso.validarUsuario(usuario, clave);
    
    if (esValido) {
        JOptionPane.showMessageDialog(rootPane, "Inicio de sesión exitoso");
        this.dispose();
        Escritorio newEscritorio = new Escritorio();
        newEscritorio.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(rootPane, "Ha fallado el Inicio de Sesión");
    }
    
    }
    
    static String CedulaPE;
    
    public void BotonAccesoCedula() {
        Queries ConsultaCedulaPE = new Queries();
        
        String user = UsuarioTxt.getText();
        String clav = new String(ClavePwd.getPassword());
        
        Acceso.CedulaPE = ConsultaCedulaPE.CedulaPE(user, clav);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClavePwd = new javax.swing.JPasswordField();
        UsuarioTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClavePwd.setBackground(new java.awt.Color(31, 124, 199));
        ClavePwd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ClavePwd.setForeground(new java.awt.Color(255, 255, 255));
        ClavePwd.setBorder(null);
        ClavePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClavePwdActionPerformed(evt);
            }
        });

        UsuarioTxt.setBackground(new java.awt.Color(31, 124, 199));
        UsuarioTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UsuarioTxt.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTxt.setBorder(null);
        UsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTxtActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/IngresarBTN.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NewAccesoBG.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ClavePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(ClavePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClavePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClavePwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClavePwdActionPerformed

    private void UsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTxtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        BotonAcceso();
        BotonAccesoCedula();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClavePwd;
    private javax.swing.JTextField UsuarioTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
