/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import Conexion.*;

/**
 *
 * @author pc personal
 */
public class NuevoAsistente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoAsistente
     */
    public NuevoAsistente() {
        initComponents();
    }
    
    
    public String ConseguirFecha() {

        String Fecha;
        String Dia = DiaTxt.getText();
        String MesX = (String) MesTxt.getSelectedItem();
        String Mes;
        String AñoXY = AñoTxt.getText();
        int AñoX = Integer.parseInt(AñoXY);
        String Año = null;
        
        switch (MesX) {
            case "Enero" -> Mes = "01";
            case "Febrero" -> Mes = "02";
            case "Marzo" -> Mes = "03";
            case "Abril" -> Mes = "04";
            case "Mayo" -> Mes = "05";
            case "Junio" -> Mes = "06";
            case "Julio" -> Mes = "07";
            case "Agosto" -> Mes = "08";
            case "Octubre" -> Mes = "09";
            case "Septiembre" -> Mes = "10";
            case "Noviembre" -> Mes = "11";
            case "Diciembre" -> Mes = "12";
            default -> throw new AssertionError();
        }
        
        boolean esMenorde1000 = (AñoX < 1000);
        if(esMenorde1000 || AñoX > 9999) {
            JOptionPane.showMessageDialog(rootPane, "Limite de caracteres en año alcanzado");
        } else {
            Año = String.valueOf(AñoX);
        }
        
        Fecha = Año+"-"+Mes+"-"+Dia;
        
        return Fecha;
    }
    
    public void InsertarRegistro() {
        Queries consulta = new Queries();
        String Nombre = NombreTxt.getText();
        String Matricula = consulta.buscarMatricula(Nombre);
        String Fecha = ConseguirFecha();
        
        consulta.RegistrarAsistente(Matricula,Fecha);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiaTxt = new javax.swing.JTextField();
        AñoTxt = new javax.swing.JTextField();
        MesTxt = new javax.swing.JComboBox<>();
        NombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DiaTxt.setBackground(new java.awt.Color(31, 124, 199));
        DiaTxt.setForeground(new java.awt.Color(255, 255, 255));
        DiaTxt.setBorder(null);
        DiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(DiaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 60, 20));

        AñoTxt.setBackground(new java.awt.Color(31, 124, 199));
        AñoTxt.setForeground(new java.awt.Color(255, 255, 255));
        AñoTxt.setBorder(null);
        getContentPane().add(AñoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 50, 20));

        MesTxt.setBackground(new java.awt.Color(31, 124, 199));
        MesTxt.setForeground(new java.awt.Color(255, 255, 255));
        MesTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(MesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 130, 30));

        NombreTxt.setBackground(new java.awt.Color(31, 124, 199));
        NombreTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setBorder(null);
        NombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTxtKeyTyped(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 350, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NewRegistrarBTN.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NuevoAsistenteBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaTxtActionPerformed

    private void NombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyTyped

    }//GEN-LAST:event_NombreTxtKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        InsertarRegistro();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñoTxt;
    private javax.swing.JTextField DiaTxt;
    private javax.swing.JComboBox<String> MesTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
