/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Conexion.Queries;
import javax.swing.JOptionPane;

/**
 *
 * @author pc personal
 */
public class NuevoMedicamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoMedicamento
     */
    public NuevoMedicamento() {
        initComponents();
    }
    
    public void InsertarRegistro() {
        Queries Consulta = new Queries();
        String Nombre = NombreTxt.getText();
        
        String CantidadX = CantidadTxt.getText();
        
        int Cantidad = Integer.parseInt(CantidadX);
        
        String Fecha = ConseguirFecha();
        
        Consulta.RegistrarMedicamento(Nombre, Cantidad, Fecha);
        
    }
    
    public String ConseguirFecha() {

        String Fecha;
        String Dia = DiaTxt.getText();
        String MesX = (String) MesTxt.getSelectedItem();
        String Mes;
        String AñoXY = AñoTxt.getText();
        int AñoX = Integer.parseInt(AñoXY);
        String Año = null;
        
        switch (MesX) {
            case "Enero" -> Mes = "01";
            case "Febrero" -> Mes = "02";
            case "Marzo" -> Mes = "03";
            case "Abril" -> Mes = "04";
            case "Mayo" -> Mes = "05";
            case "Junio" -> Mes = "06";
            case "Julio" -> Mes = "07";
            case "Agosto" -> Mes = "08";
            case "Octubre" -> Mes = "09";
            case "Septiembre" -> Mes = "10";
            case "Noviembre" -> Mes = "11";
            case "Diciembre" -> Mes = "12";
            default -> throw new AssertionError();
        }
        
        boolean esMenorde1000 = (AñoX < 1000);
        if(esMenorde1000 || AñoX > 9999) {
            JOptionPane.showMessageDialog(rootPane, "Limite de caracteres en año alcanzado");
        } else {
            Año = String.valueOf(AñoX);
        }
        
        Fecha = Año+"-"+Mes+"-"+Dia;
        
        return Fecha;
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiaTxt = new javax.swing.JTextField();
        CantidadTxt = new javax.swing.JTextField();
        AñoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        MesTxt = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DiaTxt.setBackground(new java.awt.Color(31, 124, 199));
        DiaTxt.setForeground(new java.awt.Color(255, 255, 255));
        DiaTxt.setBorder(null);
        getContentPane().add(DiaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 40, 30));

        CantidadTxt.setBackground(new java.awt.Color(31, 124, 199));
        CantidadTxt.setForeground(new java.awt.Color(255, 255, 255));
        CantidadTxt.setBorder(null);
        getContentPane().add(CantidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 30));

        AñoTxt.setBackground(new java.awt.Color(31, 124, 199));
        AñoTxt.setForeground(new java.awt.Color(255, 255, 255));
        AñoTxt.setBorder(null);
        getContentPane().add(AñoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 50, 20));

        NombreTxt.setBackground(new java.awt.Color(31, 124, 199));
        NombreTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setBorder(null);
        NombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTxtKeyTyped(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 350, 30));

        MesTxt.setBackground(new java.awt.Color(31, 124, 199));
        MesTxt.setForeground(new java.awt.Color(255, 255, 255));
        MesTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(MesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/RegistrarBTN2.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 120, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NuevoMedicamentoBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        InsertarRegistro();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void NombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyTyped

    }//GEN-LAST:event_NombreTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñoTxt;
    private javax.swing.JTextField CantidadTxt;
    private javax.swing.JTextField DiaTxt;
    private javax.swing.JComboBox<String> MesTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
