/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;
import Conexion.*;
/**
 *
 * @author pc personal
 */
public class NuevoEstudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoEstudiante
     */
    public NuevoEstudiante() {
        initComponents();
    }
    
    private int ConseguirCurso() {
    
        String CursoX = (String) CursoCB.getSelectedItem();
        int Curso;
        
        switch (CursoX) {
            case "5to Desarrollo A":
                Curso = 1242;
                break;
            case "6to Cuidados":
                Curso = 2242;
                break;
            case "5to Gestion":
                Curso = 6242;
                break;
            case "4to Mercadeo":
                Curso = 6652;
                break;
            case "4to Turismo":
                Curso = 8742;
                break;
            default:
                throw new AssertionError();
        }
        
        return Curso;
    }
    
    private void InsertarRegistro() {
        Queries consulta = new Queries();
        String Matricula = MatriculaTxt.getText();
        String Nombre1 = Nombre1Txt.getText();
        String Nombre2 = Nombre2Txt.getText();
        String Apellido1 = Apellido1Txt.getText();
        String Apellido2 = Apellido2Txt.getText();
        int Curso = ConseguirCurso();
        String EdadX = EdadTxt.getText();
        int Edad = Integer.parseInt(EdadX);
        
        consulta.NuevoEstudiante(Matricula, Nombre1, Nombre2, Apellido1, Apellido2, Edad, Curso);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MatriculaTxt = new javax.swing.JTextField();
        Apellido1Txt = new javax.swing.JTextField();
        Nombre1Txt = new javax.swing.JTextField();
        EdadTxt = new javax.swing.JTextField();
        Apellido2Txt = new javax.swing.JTextField();
        Nombre2Txt = new javax.swing.JTextField();
        CursoCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Estudiante");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MatriculaTxt.setBackground(new java.awt.Color(31, 124, 199));
        MatriculaTxt.setForeground(new java.awt.Color(255, 255, 255));
        MatriculaTxt.setBorder(null);
        MatriculaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(MatriculaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 30));

        Apellido1Txt.setBackground(new java.awt.Color(31, 124, 199));
        Apellido1Txt.setForeground(new java.awt.Color(255, 255, 255));
        Apellido1Txt.setBorder(null);
        Apellido1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1TxtActionPerformed(evt);
            }
        });
        getContentPane().add(Apellido1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, 30));

        Nombre1Txt.setBackground(new java.awt.Color(31, 124, 199));
        Nombre1Txt.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1Txt.setBorder(null);
        Nombre1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1TxtActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, 30));

        EdadTxt.setBackground(new java.awt.Color(31, 124, 199));
        EdadTxt.setForeground(new java.awt.Color(255, 255, 255));
        EdadTxt.setBorder(null);
        EdadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadTxtActionPerformed(evt);
            }
        });
        getContentPane().add(EdadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 30, 20));

        Apellido2Txt.setBackground(new java.awt.Color(31, 124, 199));
        Apellido2Txt.setForeground(new java.awt.Color(255, 255, 255));
        Apellido2Txt.setBorder(null);
        Apellido2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2TxtActionPerformed(evt);
            }
        });
        getContentPane().add(Apellido2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 110, 30));

        Nombre2Txt.setBackground(new java.awt.Color(31, 124, 199));
        Nombre2Txt.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2Txt.setBorder(null);
        Nombre2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre2TxtActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 100, 30));

        CursoCB.setBackground(new java.awt.Color(31, 124, 199));
        CursoCB.setForeground(new java.awt.Color(255, 255, 255));
        CursoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5to Desarrollo A", "6to Cuidados", "5to Gestion", "4to Mercadeo", "4to Turismo" }));
        getContentPane().add(CursoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NewRegistrarBTN.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 372, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Multimedia/NuevoEstudianteBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriculaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaTxtActionPerformed

    private void Apellido1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1TxtActionPerformed

    private void Nombre1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1TxtActionPerformed

    private void EdadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadTxtActionPerformed

    private void Apellido2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2TxtActionPerformed

    private void Nombre2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2TxtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        InsertarRegistro();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1Txt;
    private javax.swing.JTextField Apellido2Txt;
    private javax.swing.JComboBox<String> CursoCB;
    private javax.swing.JTextField EdadTxt;
    private javax.swing.JTextField MatriculaTxt;
    private javax.swing.JTextField Nombre1Txt;
    private javax.swing.JTextField Nombre2Txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
